/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   anypoint-styles.html
 */

/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="colors.d.ts" />
/// <reference path="typography.d.ts" />
/// <reference path="anypoint-theme.d.ts" />

/**
 * The `<anypoint-styles>` component provides simple ways to use Anypoint CSS styles
 * in an application. The following imports are available:
 *
 * 1. [colors.html](https://github.com/advanced-rest-client/anypoint-styles/blob/master/colors.html):
 * a complete list of the colors defined in the Anypoint [palette](http://ux.mulesoft.com/#/colors)
 *
 * 2. [typography.html](https://github.com/advanced-rest-client/anypoint-styles/blob/master/typography.html):
 * Anypoint [font](http://ux.mulesoft.com/#/typography) styles and sizes
 *
 * 3. [dropdown-menu.html](https://github.com/advanced-rest-client/anypoint-styles/blob/master/dropdown-menu.html):
 * Styles to style `paper-dropdown-menu` as anypoint component.
 *
 * 4. [anypoint-theme.html](https://github.com/advanced-rest-client/anypoint-styles/blob/master/anypoint-theme.html):
 * Default theme for anypoint applications.
 *
 * We recommend importing each of these individual files, and using the style mixins
 * available in each ones, rather than the aggregated `anypoint-styles.html` as a whole.
 */
interface AnypointStylesElement extends Polymer.Element {
}

interface HTMLElementTagNameMap {
  "anypoint-styles": AnypointStylesElement;
}
