/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   din-pro.html
 */

/// <reference path="../polymer/types/lib/elements/custom-style.d.ts" />

